### ISSUE TITLE
The veridex-mac.zip test results provided by the project are inconsistent with the official tools provided.

### ISSUE THREAD

**Issue by githubMayajie** [hansionit/Veridex#2]
this project tools result:
![image](https://user-images.githubusercontent.com/12011310/64142689-9f287100-ce3f-11e9-8b97-cccbb0eec80b.png)

android source tools result:
![image](https://user-images.githubusercontent.com/12011310/64142643-7607e080-ce3f-11e9-96fc-12673e8d90a6.png)

chinese:该项目提供的检测结果和我在官网下载最新的结果不一致，相差很大，而且有些地方代码中压根就没有使用，或者类名检测失败，我使用的mac平台下的工具，稍后我会提供一个pull

**Comment by hansionit** [comment]
你说的对，推荐大家使用最近的更新。You're right. I recommend you to use the latest update.
